name: CI

# Controls when the action will run.
# Since all changes should go through pull request, workflow will always run
# for PRs.
# Once we merge a PR, we want to run this workflow one final time on the master
# branch for verification and so the push event is only triggered for that
# branch.
on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 14.16.0

    - name: Check editorconfig formatting
      uses: editorconfig-checker/action-editorconfig-checker@main

    - name: Install Dependencies
      run: yarn install

    - name: Test and Lint
      run: yarn test
